name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
    test_and_analyze:
        name: Test & Analyze
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0 
          
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.10'
              
          - uses: actions/cache@v2
            with:
              path: ~/.cache/pip
              key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          
          - name: Install dependencies
            run: pip install -r requirements.txt
          
          - name: Install tox
            run: pip install tox
          - name: Run tox
            run: tox -e py
          
          - name: SonarCloud Scan
            uses: SonarSource/sonarcloud-github-action@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
